title: Dehua Wu's Homepage
page-top-title: Dehua Wu
top-section-bg-text: Cognitive & Developmental Psychology
home-subtitle: Dehua Wu&ensp;|&ensp;吴德华
copyright-text: '&copy; Dehua Wu 2025-2026. All Rights Reserved.'
